spring:
    devtools:
        livereload:
            enabled: false
    datasource:
        password: ${POSTGRES_PASSWORD:root}
        url: jdbc:postgresql://${POSTGRES_HOST:postgresql}:${POSTGRES_PORT:5432}/${POSTGRES_DB:my_db}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
        username: ${POSTGRES_USER:root}
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                naming:
                    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    profiles: prod
